name: Update README

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update README Stats
        run: |
          curl -o README_STATS.md "https://github-readme-stats.vercel.app/api?username=2ckdaks&count_private=true&include_all_commits=true&show_icons=true&theme=tokyonight"
        env:
          GITHUB_STATS_TOKEN: ${{ secrets.GITHUB_STATS_TOKEN }}

      - name: Commit and Push changes
        run: |
          git config --global user.name '2ckdaks'
          git config --global user.email '2ckdaks@gmail.com'
          git add README.md
          git commit -m "Update README with GitHub Stats"
          git push
